Aggregate temporal process
openEOPlatform/openeo-pg-evalscript-converter pull request #65
Opened 2022-04-05 14:04 UTC by mitjak

https://git.sinergise.com/team-6/openeo-platform/-/issues/142

2022-04-11 10:13 UTC, dgostencnik reviewed
I think integration test(s) could also be added here, at least for [Example #1](https://processes.openeo.org/#aggregate_temporal)

2022-04-14 15:28 UTC, dgostencnik approved these changes

2022-04-14 16:33 UTC, Ardweaden requested changes

2022-04-14 16:33 UTC, Ardweaden commented on tests/unit_tests/test_aggregate_temporal.py
> +            run_process(
Can `test_aggregate_temporal_exceptions` be changed to use `run_input_validation` method?

It turns out there is a major bug with the tests for exceptions discovered in https://github.com/openEOPlatform/openeo-pg-evalscript-converter/pull/68. When that is merged, this test will fail on Windows devices.

The problem is that the `exc.value` (that we check includes `error_message`) is of form: `Command "node -e <entire-code> failed with exit code 1`.  So for as long your `error_message` string is in the source code, the test will pass...

`run_input_validation` correctly checks against `stderr` attribute of `subprocess.CalledProcessError`, but it also simplifies things.

2022-04-15 07:26 UTC, Ardweaden approved these changes

2022-04-15 07:55 UTC, merged