Fix apply_dimension
openEOPlatform/openeo-pg-evalscript-converter pull request #80
Opened 2022-06-08 15:04 UTC by Ardweaden

Closes https://git.sinergise.com/team-6/openeo-platform/-/issues/166

2022-06-08 15:22 UTC, zcernigoj requested changes

2022-06-10 11:48 UTC, Ardweaden commented on src/pg_to_evalscript/javascript_datacube/DataCube.js
> +            this.dimensions[axis].labels = []
You're right. We consider an empty labels array "enumerated labels" with no explicit labels, but they indeed say specifically how it should be.

2022-06-10 12:56 UTC, zcernigoj commented on src/pg_to_evalscript/javascript_datacube/DataCube.js
> +            this.dimensions[axis].labels = []
Looks good now.

2022-06-10 12:56 UTC, zcernigoj approved these changes

2022-06-10 13:13 UTC, merged